apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: nada-frontend
  namespace: nada
  labels:
    team: nada
spec:
  # Note: As the backend URL is baked into source at build time,
  # the environment has been moved to the Dockerfile.
  image: {{ image }}
  port: 3000
  ingresses:
    - "https://data.dev.intern.nav.no/"
  accessPolicy:
    outbound:
      rules:
        - application: nada-backend
