name: "Build and deploy"
on: [workflow_dispatch, push]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      - name: Push docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: nada
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    env:
      IMAGE: ${{ needs.build.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          VAR: image=${{ needs.build-and-push.outputs.image }},ingress=https://data.intern.dev.nav.no/
          RESOURCE: .nais/nais.yaml

  deploy-prod:
    runs-on: ubuntu-latest
    needs: [build, deploy-dev]
    env:
      IMAGE: ${{ needs.build.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to prod
        if: github.ref == 'refs/heads/main'
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          VAR: image=${{ needs.build-and-push.outputs.image }},ingress=https://data.intern.nav.no/
          RESOURCE: .nais/nais.yaml,.nais/alert.yaml
